manipulator:
  # kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  # kinematics_solver: ur_kinematics/UR10KinematicsPlugin
  # kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin

  # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  # solve_type: Distance

  # kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  # # optional parameters for caching:
  # max_cache_size: 10000
  # min_pose_distance: 1
  # min_joint_config_distance: 4

  # kinematics_solver: bio_ik/BioIKKinematicsPlugin
  # kinematics_solver_search_resolution: 0.005
  # kinematics_solver_timeout: 0.005
